create table if not exists public.review_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  word_key text not null,
  rating smallint not null check (rating between 1 and 4),
  response_time_ms integer not null check (response_time_ms >= 0),
  correct boolean not null,
  reviewed_at timestamptz not null,
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.review_logs
  add column if not exists updated_at timestamptz;

update public.review_logs
set reviewed_at = timezone('utc', now())
where reviewed_at is null;

update public.review_logs
set updated_at = coalesce(updated_at, reviewed_at, timezone('utc', now()))
where updated_at is null;

alter table public.review_logs
  alter column rating type smallint using rating::smallint,
  alter column reviewed_at set not null,
  alter column reviewed_at drop default,
  alter column updated_at set default timezone('utc', now()),
  alter column updated_at set not null,
  drop column if exists mode;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.review_logs'::regclass
      and conname = 'review_logs_rating_check'
  ) then
    alter table public.review_logs
      add constraint review_logs_rating_check
      check (rating between 1 and 4);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.review_logs'::regclass
      and conname = 'review_logs_response_time_ms_check'
  ) then
    alter table public.review_logs
      add constraint review_logs_response_time_ms_check
      check (response_time_ms >= 0);
  end if;
end
$$;

create unique index if not exists review_logs_user_word_reviewed_at_key
  on public.review_logs (user_id, word_key, reviewed_at);

create index if not exists review_logs_user_reviewed_at_idx
  on public.review_logs (user_id, reviewed_at desc);

alter table public.review_logs enable row level security;

drop policy if exists "users_own_logs" on public.review_logs;
drop policy if exists "Users can read own review logs" on public.review_logs;
drop policy if exists "Users can insert own review logs" on public.review_logs;
drop policy if exists "Users can update own review logs" on public.review_logs;

create policy "Users can read own review logs"
  on public.review_logs
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own review logs"
  on public.review_logs
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own review logs"
  on public.review_logs
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
